### ISSUE TITLE
Providing own filter function

### ISSUE THREAD

**Issue by profhase** [Juravenator/paper-dropdown-input#2]
Hi, thanks for the great element.

The data I get from ajax has a different attribute to filter for than value. Is there a way to provide custom filtering function (as in dom-repeat)?

Thanks a lot

**Comment by Juravenator** [comment]
The `filter` property is a function, using which you can supply your own filter function and filter based on a property different than `value`.

However, I see that in [one place](https://github.com/Juravenator/paper-dropdown-input/blob/4bd4769600e77ca2f5fd0a8a355a107b6335dde7/paper-dropdown-input.html#L659) I hardcoded the `value` property, so I'll need to update that part to truly support this.

**Comment by Juravenator** [comment]
The previous commit added a property `filterProperty`, which specifies which property name to use when filtering objects. I will publish a new release shortly.

**Comment by profhase** [comment]
Thanks a lot
