### ISSUE TITLE
Like it..but...

### ISSUE THREAD

**Issue by Stefdv** [Juravenator/paper-dropdown-input#3]
I really like it, but i would prefer to have the input NOT in the dropdown. I also miss the option to just show the list without searching.

**Comment by Juravenator** [comment]
The 1.x versions actually had the input field and the search field combined like you say. But user feedback was very bad, they didn't know how to operate the element and this created frustration.
The approach as it is currently is understood right off the bat by everyone.

About turning off search, how does a `no-search` option sound?

**Comment by Juravenator** [comment]
`no-search` added in 3c76025a2b570125b7e8761a9a10b5d19ee3179e
